#!perl

use strict;
use warnings;

use vars '$name', '$gender';
use ScriptX (
    'Getopt::Long' => {
        spec => ['name=s' => \$name, 'gender=s' => \$gender],
    },
    'Run',
);

sub run {
    my ($self, $stash) = @_;

    unless ($name) {
        print "Please specify --name!\n";
        exit 1;
    }
    unless ($gender) {
        print "Please specify --gender!\n";
        exit 1;
    }
    unless ($gender =~ /\A[mf]\z/i) {
        print "Invalid value in --gender, please specify m|f!\n";
        exit 1;
    }

    print "Hello, ", ($gender =~ /m/i ? "Mr." : "Mrs."), " $name!\n";
}

ScriptX->run;

# ABSTRACT: Parse command-line options using simple heuristics (demos debugging by dumping stash)
# PODNAME:

=head1 SYNOPSIS

 % script-eg-getopt-specless
 Please specify --name!

 % script-eg-getopt-specless --name=Budi
 Please specify --gender!

 % script-eg-getopt-specless --name=Budi --gender=x
 Invalid value in --gender, please specify m|f!

 % script-eg-getopt-specless --name=Budi --gender=m
 Hello, Mr. Budi!


=head1 DESCRIPTION

This script demonstrates the use of L<ScriptX::Getopt::Long> which, admittedly,
does not do much. It's okay if you want to load and use L<Getopt::Long>
directly.


=head1 SEE ALSO

L<scriptx-eg-getopt-specless>
